/**
 * Static city dataset — US cities with population >= 25,000.
 * Source: dr5hn/countries-states-cities-database (ODbL license).
 * Generated by scripts/generate-city-data.mjs
 */

import { haversineDistance } from './geo-utils'
import citiesJson from '../../data/us-cities-25k.json'

export interface CityEntry {
  city: string
  state_code: string
  slug: string
  lat: number
  lng: number
  population: number
}

const cities: CityEntry[] = citiesJson as CityEntry[]

// ── Indexes for fast lookups ────────────────────────────────────────────

/** Map: "STATE:slug" → CityEntry */
const bySlug = new Map<string, CityEntry>()
/** Map: "STATE" → CityEntry[] (sorted by population desc) */
const byState = new Map<string, CityEntry[]>()

for (const c of cities) {
  bySlug.set(`${c.state_code}:${c.slug}`, c)
  const list = byState.get(c.state_code) ?? []
  list.push(c)
  byState.set(c.state_code, list)
}

// ── Exports ─────────────────────────────────────────────────────────────

/** Look up a single city by slug + state code. */
export function getCityBySlug(slug: string, stateCode: string): CityEntry | null {
  return bySlug.get(`${stateCode.toUpperCase()}:${slug}`) ?? null
}

/** All cities in a state, sorted by population desc. */
export function getCitiesForState(stateCode: string): CityEntry[] {
  return byState.get(stateCode.toUpperCase()) ?? []
}

/**
 * Nearby cities in the same state, sorted by haversine distance.
 * Excludes the city matching `excludeSlug`.
 */
export function getNearbyCities(
  lat: number,
  lng: number,
  stateCode: string,
  excludeSlug: string,
  limit = 12,
): CityEntry[] {
  const stateCities = getCitiesForState(stateCode)
  return stateCities
    .filter((c) => c.slug !== excludeSlug)
    .map((c) => ({ ...c, _dist: haversineDistance(lat, lng, c.lat, c.lng) }))
    .sort((a, b) => a._dist - b._dist)
    .slice(0, limit)
}

/** Full dataset (for sitemap generation). */
export function getAllCities(): CityEntry[] {
  return cities
}

/**
 * Simple deterministic hash of a string → number.
 * Used for rotating FAQ selection per city.
 */
export function hashString(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) - h + s.charCodeAt(i)) | 0
  }
  return Math.abs(h)
}
